# Дополнительные задачи


## Распределение НБА

Задача 1

Перед каждым сезоном НБА проходит драфт, то есть церемония выбора игроков командами.
Перед драфтом скаутские службы команд детально изучают потенциальных новичков. Одна из команд поручила вам написать программу для обработки собранных данных в соответствии с внутрикомандными стандартами.

Каждый из новичков до этого провёл как минимум один сезон в студенческих лигах, так что для каждого игрока известны пять основных целочисленных параметров:

●	Рост игрока – ожидаемый диапазон от 190 до 220 см.
●	Размах рук (иначе говоря, wingspan) – ожидаемый диапазон от 200 до 250 см.
●	Среднее количество очков за матч – ожидаемый диапазон от 10 до 20.
●	Среднее количество подборов за матч – ожидаемый диапазон от 2 до 6.
●	Среднее количество передач за матч – ожидаемый диапазон от 3 до 7.

Таким образом, каждый из параметров может оказаться ниже ожидаемого диапазона, в нижней половине ожидаемого диапазона, в верхней половине ожидаемого диапазона (середина входит в верхнюю половину) и выше ожидаемого диапазона.
Перед драфтом требуется распределить игроков по следующим категориям:

●	уникальный игрок (таких ещё называют «единорогами» — unicorn) с сочетанием выдающихся физических данных и игровых навыков;
●	игрок, достойный выбора в первом раунде;
●	игрок, достойный выбора во втором раунде;
●	игрок, которого не стоит выбирать вообще.

Если у игрока три параметра выше ожидаемого диапазона, причём среди них обязательно есть рост или размах рук, то игрок считается «единорогом» (категория 0)

Игрока рекомендуется выбирать в первом раунде драфта (категория 1), если верно одно из следующих утверждений:

●	У игрока два параметра выше ожидаемого диапазона и ещё один – как минимум в верхней половине ожидаемого диапазона.
●	У игрока все параметры как минимум в ожидаемом диапазоне и не менее трёх – как минимум в верхней половине.

Игрока рекомендуется выбирать во втором раунде драфта (категория 2), если верно одно из следующих утверждений:
●	У игрока один параметр выше ожидаемого диапазона и ещё один — как минимум в верхней половине ожидаемого диапазона.
●	У игрока три параметра как минимум в верхней половине ожидаемого диапазона.

В остальных случаях тратить выбор драфта на этого игрока не рекомендуется (категория 3).
Вам заданы параметры некоторых из 32 игроков текущего драфта (для объективности имена игроков не указаны). Ваша задача – для каждого игрока определить категорию, под которую он подпадает для вашей команды на драфте.


In [1]:
def igrok(rost,razmah, ochki, podbor, peredach):
    luchiy = 0; verx = 0; niz = 0; plox = 0
    
    if rost > 220: 
        luchiy = luchiy + 1
    elif rost > 204 and rost <= 220: 
        verx = verx + 1
    elif rost >= 190 and rost <= 204: 
        niz = niz + 1
    else:
         plox =  plox + 1
        
    if razmah > 250:
        luchiy = luchiy + 1
    elif razmah > 224 and razmah <= 250: 
        verx = verx + 1
    elif razmah >= 200 and razmah <= 224: 
        niz = niz + 1
    else:
         plox =  plox + 1
        
    if ochki > 20:
        luchiy = luchiy + 1
    elif ochki > 14 and ochki <= 20: 
        verx = verx + 1
    elif ochki >= 10 and ochki <= 14: 
        niz = niz + 1
    else:
        plox =  plox + 1
    
    if podbor > 6:
        luchiy = luchiy + 1
    elif podbor > 4 and podbor <= 6: 
        verx = verx + 1
    elif podbor >= 2 and podbor <= 4: 
        niz = niz + 1
    else: 
         plox =  plox + 1
        
    if peredach > 7:
        luchiy = luchiy + 1
    elif peredach > 4 and peredach <= 7:
        verx = verx + 1
    elif peredach >= 3 and peredach <= 4: 
        niz = niz + 1
    else:
        plox =  plox + 1
    
    if luchiy >= 3 and (rost > 220 or razmah > 250): 
        return 0
    elif (luchiy >= 2 and verx >= 1) or (verx >= 3 and niz <= 2 and  plox == 0):
        return 1
    elif (luchiy >= 1 and verx >= 1) or (verx >= 3): 
        return 2
    else: 
        return 3

In [2]:
print(igrok(230, 190, 16, 7, 9))
print(igrok(205, 225, 15, 5, 2))
print(igrok(210, 210, 30, 9, 9))

0
2
1


##  Треугольник с максимальным периметром

Массив A состоит из целых положительных чисел - длин отрезков. Составьте из трех отрезков такой треугольник, чтобы его периметр был максимально возможным. Если невозможно составить треугольник с положительной площадью - функция возвращает 0.

In [6]:
length = int(input("кол-во эл. = "))
def massive(length):
    array = []
    print("Элементы массива")
    for i in range(length):
        array.append(int(input()))
    return array
mas = massive(length)
def puzir(arr):
    for i in range(length-1):
        for j in range(length-i-1):
            if arr[j] < arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
    return arr

print(puzir(mas))

def max_per(arr):
    for i in range(length-2):
        if arr[i]+arr[i+1] > arr[i+2] and arr[i]+arr[i+2] > arr[i+1] and arr[i+2]+arr[i+1] > arr[i]:
            per = arr[i] + arr[i+1] + arr[i+2]
            return per
    return 0
print(max_per(mas))

кол-во эл. = 2
Элементы массива
1
2
[2, 1]
0


##  Максимальное число


Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [7]:
import numpy
from copy import deepcopy


def biggest_first_number(row):
    ans_row = deepcopy(row)

    max = -3
    for i in range(len(row)):
        if ans_row[i][0] >= max:
            max = ans_row[i][0]
    for i in range(len(row)):
        if ans_row[i][0] != max and ans_row[i][0] >= 0:
            ans_row[i][0] = -2
    return ans_row


def add_best_numbers(row, original_row):
    big_number = ''
    isNeededToBeChecked = False

    for i in range(len(row)):
        if row[i][0] >= 0:
            if len(row[i]) == 1:
                big_number += str(''.join(map(str, original_row[i])))
                row[i][0] = -1
            else:
                row[i].__delitem__(0)
                isNeededToBeChecked = True

    length = len(row)
    i = 0
    while i < length:  # удаляем добавленные числа
        if row[i][0] == -1:
            original_row.__delitem__(i)
            row.__delitem__(i)
            length -= 1
        else:
            i += 1

    if isNeededToBeChecked:
        best_numbers = biggest_first_number(row)
        big_number += add_best_numbers(best_numbers, original_row)
    return big_number


def find_max(row):
    length = len(row)
    big_number = ''

    raw_row = [''] * length

    for i in range(length):
        number = str(row[i])  # превращаем наши числа в массив символов
        raw_row[i] = list(number)  # записываем наш массив в массив
        raw_row[i] = [int(raw_row[i]) for raw_row[i] in raw_row[i]]


    while len(raw_row) != 0:
        best_numbers = biggest_first_number(raw_row)  # находим лучших кандидатов

        big_number += add_best_numbers(best_numbers, raw_row)


    return big_number










row = numpy.random.randint(1, 150, size=10)
print(row)
result = find_max(row)
print(result)

[138 147  29   2 120   7  37  74  97   3]
97774337229147138120


## Сортировка диагоналей в матрице

Дан массив неотрицательных целых чисел nums. Расположите их в таком порядке, чтобы
вместе они образовали максимально возможное число.

In [8]:
import numpy

def sort_matrix(mat):
    height = len(mat)
    width = len(mat[0])

    for x_start in range(1, width):
        line = []
        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            line.append(mat[y][x])
            x += 1
        #print(line)
        line.sort()
        #print(line)

        x = x_start
        for y in range(height - (0 if width - height - x >= 0 else abs(width - height - x)) ):
            mat[y][x] = line[y]
            x += 1

    for y_start in range(0, height):
        line = []
        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            line.append(mat[y][x])
            y += 1
        #print(line)
        line.sort()
        #print(line)

        y = y_start
        for x in range(width - (0 if height - width - y >= 0 else abs(height - width - y)) ):
            mat[y][x] = line[x]
            y += 1


matrix = numpy.random.randint(0, 10, size=(10,4))
print(matrix)

sort_matrix(matrix)
print(matrix)


w, h = 8, 5


[[6 8 7 4]
 [0 5 1 9]
 [2 2 0 6]
 [7 2 2 2]
 [2 8 1 3]
 [1 6 5 0]
 [3 4 0 8]
 [9 7 0 9]
 [5 0 8 1]
 [2 4 8 0]]
[[0 1 7 4]
 [0 2 6 9]
 [0 2 5 8]
 [5 1 2 6]
 [0 7 2 3]
 [0 2 8 2]
 [0 1 6 8]
 [0 3 1 9]
 [4 8 7 4]
 [2 5 9 8]]


В Тридевятом Царстве уже много лет как установилась конституционная монархия. В парламент Тридевятого царства входят 26 партий, обозначаемых строчными буквами английского алфавита от «a» до «z». Заседание парламента в соответствии с регламентом проходит по следующей схеме:
*	В начале заседания никаких законопроектов на повестке дня не стоит.
*	Любая партия (в том числе и та, которая внесла текущий законопроект) в любой момент времени может внести на обсуждение новый законопроект.
*	При вносе партией нового законопроекта обсуждение предыдущего приостанавливается и начинается обсуждение нового. После того, как парламентарии голосуют за новый законопроект, обсуждение законопроекта, прерванного им, продолжается.
*	Дискуссия по любому законопроекту обязана завершиться голосованием по этому законопроекту.
*	В конце заседания не должно остаться внесённых законопроектов, дискуссия по которым не завершена.
Вам дана запись о событиях на сессии парламента. Каждое событие является либо внесением нового законопроекта, либо голосованием за какой-то законопроект, причём в обоих случаях известен номер партии, этот законопроект предложившей. События даны в том порядке, в котором они происходили. Проверьте, может ли данная запись о событиях соответствовать какому-либо заседанию, удовлетворяющему порядку проведения, описанному выше.


Входные данные

Первая строка входных данных содержит одно целое число K – количество строк в записи сессии (1 ≤ K ≤ 1000). Каждая строка соответствует одному из двух событий:

Add x – партия x внесла на голосование законопроект.
Vote x – прошло голосование за документ, внесённый партией x.
Здесь x – строчная буква английского алфавита от «a» до «z», задающая партию.

Вывод

Выведите «Yes», если существует корректный порядок проведения заседания, который мог привести к такой записи, и «No», если ни при каком корректном порядке проведения заседания данная запись появиться не могла.

In [22]:
def check(events):
    stack = []
    for e in events:
        cmd, party = e.split()
        if cmd == "Add":
            stack.append(party)
        elif stack.pop() != party:
            return "No"
    return "Yes" if len(stack) == 0 else "No"

#assert check(["Add x", "Add y", "Vote y", "Vote x"]) == "Yes"
#assert check(["Add x", "Add x", "Vote y", "Vote x"]) == "No"
#assert check(["Add x", "Add y"]) == "No"
check(["Add x", "Vote x"])

'Yes'

### Правильный подмногоугольник
Задан правильный N-угольник. Требуется выбрать наименьшее количество его вершин, которые также образуют правильный многоугольник.

Входные данные

Входные данные содержат одно целое число N (3 ≤ N ≤ 10^12).

Вывод

Выведите одно число — наименьшее количество вершин заданного многоугольника, которые образуют правильный многоугольник.

In [21]:
def subpolygon(N):
    for i in range(3, int(N**.5)+1):  # так максимум проверок 10^6  
        if N % i == 0: return i
    if N > 4 and N % 2 == 0:
        # многоугольника из 2 вершин не существует
        # но второй множитель явно больше 2 (для N > 4), поэтому если ничего из цикла не подошло
        # то это число нам подходит
        return N / 2
    return N

subpolygon(3) 
#assert subpolygon(4) == 4
#assert subpolygon(8) == 4
#assert subpolygon(9) == 3
#assert subpolygon(10) == 5
#assert subpolygon(11) == 11
#assert subpolygon(16) == 4
#assert subpolygon(5942430146) == 2971215073

3

На форуме, на котором обсуждаются задачи олимпиад по информатике, ввели следующий аналог капчи. Участнику выдаётся строка из N десятичных цифр (без ведущих нулей). В качестве ответа требуется ввести такое основание системы счисления B, что в этой системе счисления выданная запись будет соответствовать составному числу (назовем его D), а также число X, большее 1 и меньшее D, являющееся делителем D.

При этом B и X не должны превосходить 10^9. По заданной строке десятичных цифр найдите любую пару чисел B и X, удовлетворяющую ограничениям, или ответьте, что решения в заданных ограничениях не существует.

Входные данные

Входные данные состоят из непустой строки длиной до 3 ⋅ 10^6 символов, составленной из цифр от 0 до 9 и не начинающейся с 0.

Вывод

Если решение существует, выведите два числа – основание системы счисления B и делитель X, записанные в десятичной системе счисления. Оба числа должны удовлетворять ограничениям 2 ≤ B, X ≤ 10^9. Если решения не существует, выведите –1.



In [19]:
def captcha(s):
    if len(s) == 1:
        res = [0,0,0,2,0,2,0,2,3][int(s)-1]
        if res:
            return 10, res
        return -1
    S = sum(map(int, s))
    if S == 1:
        return 10, 2
    return S + 1, S

#assert captcha('5') == -1
#assert captcha('8') == (10, 2)
#assert captcha('10') == (10, 2)
captcha("19")

(11, 10)

### Объединение отрезков

Дан массив отрезков intervals, в котором intervals[i] = [starti
, endi
], некоторые
отрезки могут пересекаться. Напишите функцию, которая объединяет все пересекающиеся отрезки в один и возвращает новый массив непересекающихся отрезков.


## Задания на строки


Даны две строки: s1 и s2 с одинаковым размером, проверьте, может ли
некоторая перестановка строки s1 “победить” некоторую перестановку
строки s2 или наоборот.
Строка x может “победить” строку y (обе имеют размер n), если x[i]> = y
[i] (в алфавитном порядке) для всех i от 0 до n-1.


Дана строка s, вернуть самую длинную полиндромную подстроку в s.

Вернуть количество отдельных непустых подстрок текста, которые могут
быть записаны как конкатенация некоторой строки с самой собой (т.е. она
может быть записана, как a + a, где a - некоторая строка).
